# Generated by Django 3.2.8 on 2021-10-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeapUser',
            fields=[
                ('user_email', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('user_ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
